services:
  - type: web
    name: habbit-forge-strapi
    env: node
    plan: starter
    buildCommand: npm install && npm run build && npm run seed:production
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: APP_KEYS
        sync: false
      - key: ADMIN_JWT_SECRET
        sync: false
      - key: API_TOKEN_SALT
        sync: false
      - key: TRANSFER_TOKEN_SALT
        sync: false
      - key: SMTP_USERNAME
        sync: false
      - key: SMTP_PASSWORD
        sync: false
    healthCheckPath: /_health
    autoDeploy: true 